notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: SCEC6qJbM6/toQ9zSGQthJmeHQ+Zl1hiuiB0CjNPzg0EooezO5CrK1MIEJH9pg2zzrry5J7FRjYv3QavtOkuSRINb4U9e3t/OxS6EQsaExPK6wphReaAoX3bR9gTZpflvmntiA+sJ9AjUR5Hl9QzisEgqagvKYT2ldYORGq5qere5oLBmlDlBsNgBGQrDVX5hwScwjJ3IT09pLTN7p9srWnnZ+dHWA+3MB5fBnnkiw0PEQ7NbByTkvuIustrq2XD1kMMxsdGmEmnqm903eN/Wh0Attlgywipm8gJggYe1iXjK/LclerZou5n0rDikfjnJwPLXc08xS55bbAj1GnwbJpeDMOJ3jb/pO23HgcFH1dxeKw1Wox/0LRwnT0fuTLkex10DqOFSYiOBxHKAWwIcLp40HL3zt6YolQNTCcCY3BuC0NU6WxlpArSvghjdiLjmc3/ftUk0RMVyGBeqzRox5MCqK+qk4E2pA7wtIHlKIlVKmENlud3/o7ITIVLxIGtt4RGFanVGNwqKu2DXyxyktUWUVFkhIflpXUMDbqr228y38IHeObeg97kEcokoT0UDVvFYv7NaEOGvuzLzEBc/LwpNZ0lW9mp7MALRcsotVCjXL88vmxXX4StGHGGL8aD+1bC6yEDGOvTJ5oEi/8a6nyX4FjZsIo/oIJpjxYUjvk=
stages:
- name: BUILD
jobs:
  include:
  - stage: BUILD
    language: node_js
    node_js:
    - '16'
    services:
    - docker
    script:
    - bash .travis.build.sh
