name: ci
on:
  push:
  workflow_dispatch:
    inputs:
      build_service:
        description: "Build service"
        default: false
        required: false
        type: boolean
      run_tests:
        description: "Run tests"
        default: false
        required: false
        type: boolean
      additional_tests:
        description: "Additional tests"
        default: false
        required: false
        type: boolean

jobs:
  run_tests:
    name: Run tests
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.run_tests ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip tests')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh
      - name: Run tests
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/run_tests.sh -r ${{ github.job }}

  additional_tests:
    strategy:
      fail-fast: false
      matrix:
        node: [ 22 ]
    name: Additional tests
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.additional_tests ||
      github.event_name == 'push' && contains(github.event.head_commit.message, 'additional tests')
      }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh -n ${{ matrix.node }}
      - name: Run tests
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/run_tests.sh -n ${{ matrix.node }}

  build_service:
    name: Build service
    if: ${{
      github.event_name == 'workflow_dispatch' && inputs.build_app ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip build')
      }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node: [ 20 ]
        debian: [ 'bookworm' ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh
      - name: Build service
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/build_service.sh -p -r ${{ github.job }} -n ${{ matrix.node }} -d ${{ matrix.debian }}
